#S pring properties

spring:
  application:
    name: chat-bot
  ai:
    chat:
      client:
        enabled: true # includes ChatClient bean
    ollama:
      base-url: http://localhost:11434 # Base URL of the local LLM (Docker)
      chat:
        options:
          model: qwen2.5 # - accurate tool calling
#         model: mistral # - not very accurate
      embedding:
        options:
          model: qwen3-embedding # default = mxbai-embed-large
    #    openai:
    #      api-key:
#    google:
#      genai:
#        api-key:

# chat-bot Service properties
chatbot:
  cli:
    enabled: false
